// Default mocks
module.exports = [
  {
    _id: '5a67434ec4cf05caeb5820d0',
    active: true,
    business: 'Business 01',
    details: 'Details 01',
    email: 'Email 01',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 01',
    notification: true,
    phone: 'Phone 01',
    position: 'Position 01',
  }, {
    _id: '5a67434ec4cf05caeb5820d1',
    active: true,
    business: 'Business 02',
    details: 'Details 02',
    email: 'Email 02',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 02',
    notification: true,
    phone: 'Phone 02',
    position: 'Position 02',
  }, {
    _id: '5a67434ec4cf05caeb5820d2',
    active: true,
    business: 'Business 03',
    details: 'Details 03',
    email: 'Email 03',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 03',
    notification: false,
    phone: 'Phone 03',
    position: 'Position 03',
  }, {
    _id: '5a67434ec4cf05caeb5820d3',
    active: true,
    business: 'Business 04',
    details: 'Details 04',
    email: 'Email 04',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 04',
    notification: false,
    phone: 'Phone 04',
    position: 'Position 04',
  }, {
    _id: '5a67434ec4cf05caeb5820d4',
    active: true,
    business: 'Business 05',
    details: 'Details 05',
    email: 'Email 05',
    logs: {
      isDeleted: true,
      test: true,
    },
    name: 'Name 05',
    notification: true,
    phone: 'Phone 05',
    position: 'Position 05',
  }, {
    _id: '5a67434ec4cf05caeb5820d5',
    active: true,
    business: 'Business 06',
    details: 'Details 06',
    email: 'Email 06',
    logs: {
      isDeleted: true,
      test: true,
    },
    name: 'Name 06',
    notification: true,
    phone: 'Phone 06',
    position: 'Position 06',
  }, {
    _id: '5a67434ec4cf05caeb5820d6',
    active: true,
    business: 'Business 07',
    details: 'Details 07',
    email: 'Email 07',
    logs: {
      isDeleted: true,
      test: true,
    },
    name: '',
    notification: true,
    phone: 'Phone 07',
    position: 'Position 07',
  }, {
    _id: '5a67434ec4cf05caeb5820d7',
    active: true,
    business: 'Business 08',
    details: 'Details 08',
    email: 'Email 08',
    logs: {
      isDeleted: true,
      test: true,
    },
    name: 'Name 08',
    notification: true,
    phone: 'Phone 08',
    position: '',
  }, {
    _id: '5a67434ec4cf05caeb5820d8',
    active: true,
    business: 'Business 09',
    details: 'Details 09',
    email: 'Email 09',
    logs: {
      isDeleted: true,
      test: true,
    },
    name: 'Name 09',
    notification: true,
    phone: '',
    position: 'Position 09',
  }, {
    _id: '5a67434ec4cf05caeb5820d9',
    active: true,
    business: 'Business 10',
    details: '',
    email: 'Email 10',
    logs: {
      isDeleted: true,
      test: true,
    },
    name: 'Name 10',
    notification: true,
    phone: 'Phone 10',
    position: 'Position 10',
  },
];
