// Default mocks
module.exports = [
  {
    _id: '5a67434ec4cf05caeb5820d0',
    active: true,
    annex: 'Annex 01',
    area: 'Area 01',
    country_code: 'Country Code 01',
    logs: {
      isDeleted: false,
      test: true,
    },
    number: 'Number 01',
    primary: true,
    validation: true,
  }, {
    _id: '5a67434ec4cf05caeb5820d1',
    active: true,
    annex: 'Annex 02',
    area: 'Area 02',
    country_code: 'Country Code 02',
    logs: {
      isDeleted: false,
      test: true,
    },
    number: 'Number 02',
    primary: true,
    validation: true,
  }, {
    _id: '5a67434ec4cf05caeb5820d2',
    active: true,
    annex: 'Annex 03',
    area: 'Area 03',
    country_code: 'Country Code 03',
    logs: {
      isDeleted: false,
      test: true,
    },
    number: 'Number 03',
    primary: false,
    validation: true,
  }, {
    _id: '5a67434ec4cf05caeb5820d3',
    active: true,
    annex: 'Annex 04',
    area: 'Area 04',
    country_code: 'Country Code 04',
    logs: {
      isDeleted: false,
      test: true,
    },
    number: 'Number 04',
    primary: false,
    validation: true,
  }, {
    _id: '5a67434ec4cf05caeb5820d4',
    active: true,
    annex: 'Annex 05',
    area: 'Area 05',
    country_code: 'Country Code 05',
    logs: {
      isDeleted: true,
      test: true,
    },
    number: 'Number 05',
    primary: true,
    validation: true,
  }, {
    _id: '5a67434ec4cf05caeb5820d5',
    active: true,
    annex: 'Annex 06',
    area: 'Area 06',
    country_code: 'Country Code 06',
    logs: {
      isDeleted: true,
      test: true,
    },
    number: 'Number 06',
    primary: true,
    validation: true,
  }, {
    _id: '5a67434ec4cf05caeb5820d6',
    active: true,
    annex: 'Annex 07',
    area: 'Area 07',
    country_code: 'Country Code 07',
    logs: {
      isDeleted: true,
      test: true,
    },
    number: '',
    primary: false,
    validation: false,
  }, {
    _id: '5a67434ec4cf05caeb5820d7',
    active: true,
    annex: 'Annex 08',
    area: 'Area 08',
    country_code: '',
    logs: {
      isDeleted: true,
      test: true,
    },
    number: 'Number 08',
    primary: false,
    validation: false,
  }, {
    _id: '5a67434ec4cf05caeb5820d8',
    active: true,
    annex: 'Annex 09',
    area: 'Area 09',
    country_code: 'Country Code 09',
    logs: {
      isDeleted: true,
      test: true,
    },
    number: '',
    primary: false,
    validation: false,
  }, {
    _id: '5a67434ec4cf05caeb5820d9',
    active: true,
    annex: 'Annex 10',
    area: '',
    country_code: 'Country Code 10',
    logs: {
      isDeleted: true,
      test: true,
    },
    number: 'Number 10',
    primary: false,
    validation: false,
  },
];
