// Declaracion de dependencias
const { getDate } = require('./sii');

// Se exportan los datos de entrada
exports.inputMapperDocument = [
  {
    dhdrCodigo: 3536982623,
    dcvCodigo: 64556344,
    dcvEstadoContab: null,
    detCodigo: 1298116950,
    detTipoDoc: null,
    detRutDoc: 76429360,
    detDvDoc: '6',
    detRznSoc: 'TELESTAR SA',
    detNroDoc: 19157,
    detFchDoc: '01/01/2019',
    detFecAcuse: null,
    detFecReclamado: null,
    detFecRecepcion: '02/01/2019 10:35:24',
    detMntExe: 0,
    detMntNeto: 336656,
    detMntActFijo: 0,
    detMntIVAActFijo: 0,
    detMntIVANoRec: 0,
    detMntCodNoRec: 0,
    detMntSinCredito: 0,
    detMntIVA: 63965,
    detMntTotal: 400621,
    detTasaImp: null,
    detAnulado: null,
    detIVARetTotal: null,
    detIVARetParcial: null,
    detIVANoRetenido: 0,
    detIVAPropio: null,
    detIVATerceros: null,
    detIVAUsoComun: 0,
    detLiqRutEmisor: null,
    detLiqDvEmisor: null,
    detLiqValComNeto: null,
    detLiqValComExe: null,
    detLiqValComIVA: null,
    detIVAFueraPlazo: null,
    detTipoDocRef: 0,
    detFolioDocRef: null,
    detExpNumId: null,
    detExpNacionalidad: null,
    detCredEc: null,
    detLey18211: null,
    detDepEnvase: null,
    detIndSinCosto: null,
    detIndServicio: null,
    detMntNoFact: null,
    detMntPeriodo: null,
    detPsjNac: null,
    detPsjInt: null,
    detNumInt: null,
    detCdgSIISucur: 0,
    detEmisorNota: 0,
    detTabPuros: 0,
    detTabCigarrillos: 0,
    detTabElaborado: 0,
    detImpVehiculo: 0,
    detTpoImp: 1,
    detTipoTransaccion: 1,
    detEventoReceptor: 'A',
    detEventoReceptorLeyenda: 'No reclamado en plazo',
    cambiarTipoTran: true,
    detPcarga: 201901,
    descTipoTransaccion: 'Del Giro',
    totalDtoiMontoImp: 0,
    totalDinrMontoIVANoR: null,
  }, {
    dhdrCodigo: 3537154869,
    dcvCodigo: 64556344,
    dcvEstadoContab: null,
    detCodigo: 1298402297,
    detTipoDoc: null,
    detRutDoc: 76578299,
    detDvDoc: '6',
    detRznSoc: 'DISEÑO SILVIO ENRIQUE VILDÓSOLA CARO E.I.R.L.',
    detNroDoc: 31,
    detFchDoc: '02/01/2019',
    detFecAcuse: null,
    detFecReclamado: null,
    detFecRecepcion: '02/01/2019 11:49:12',
    detMntExe: 0,
    detMntNeto: 101000,
    detMntActFijo: 0,
    detMntIVAActFijo: 0,
    detMntIVANoRec: 0,
    detMntCodNoRec: 0,
    detMntSinCredito: 0,
    detMntIVA: 19190,
    detMntTotal: 120190,
    detTasaImp: null,
    detAnulado: null,
    detIVARetTotal: null,
    detIVARetParcial: null,
    detIVANoRetenido: 0,
    detIVAPropio: null,
    detIVATerceros: null,
    detIVAUsoComun: 0,
    detLiqRutEmisor: null,
    detLiqDvEmisor: null,
    detLiqValComNeto: null,
    detLiqValComExe: null,
    detLiqValComIVA: null,
    detIVAFueraPlazo: null,
    detTipoDocRef: 0,
    detFolioDocRef: null,
    detExpNumId: null,
    detExpNacionalidad: null,
    detCredEc: null,
    detLey18211: null,
    detDepEnvase: null,
    detIndSinCosto: null,
    detIndServicio: null,
    detMntNoFact: null,
    detMntPeriodo: null,
    detPsjNac: null,
    detPsjInt: null,
    detNumInt: null,
    detCdgSIISucur: 80313898,
    detEmisorNota: 0,
    detTabPuros: 0,
    detTabCigarrillos: 0,
    detTabElaborado: 0,
    detImpVehiculo: 0,
    detTpoImp: 1,
    detTipoTransaccion: 1,
    detEventoReceptor: 'A',
    detEventoReceptorLeyenda: 'No reclamado en plazo',
    cambiarTipoTran: true,
    detPcarga: 201901,
    descTipoTransaccion: 'Del Giro',
    totalDtoiMontoImp: 0,
    totalDinrMontoIVANoR: null,
  }, {
    dhdrCodigo: 3537234022,
    dcvCodigo: 64556344,
    dcvEstadoContab: null,
    detCodigo: 1298531507,
    detTipoDoc: null,
    detRutDoc: 76578299,
    detDvDoc: '6',
    detRznSoc: 'DISEÑO SILVIO ENRIQUE VILDÓSOLA CARO E.I.R.L.',
    detNroDoc: 33,
    detFchDoc: '02/01/2019',
    detFecAcuse: null,
    detFecReclamado: null,
    detFecRecepcion: '02/01/2019 12:23:19',
    detMntExe: 0,
    detMntNeto: 140000,
    detMntActFijo: 0,
    detMntIVAActFijo: 0,
    detMntIVANoRec: 0,
    detMntCodNoRec: 0,
    detMntSinCredito: 0,
    detMntIVA: 26600,
    detMntTotal: 166600,
    detTasaImp: null,
    detAnulado: null,
    detIVARetTotal: null,
    detIVARetParcial: null,
    detIVANoRetenido: 0,
    detIVAPropio: null,
    detIVATerceros: null,
    detIVAUsoComun: 0,
    detLiqRutEmisor: null,
    detLiqDvEmisor: null,
    detLiqValComNeto: null,
    detLiqValComExe: null,
    detLiqValComIVA: null,
    detIVAFueraPlazo: null,
    detTipoDocRef: 0,
    detFolioDocRef: null,
    detExpNumId: null,
    detExpNacionalidad: null,
    detCredEc: null,
    detLey18211: null,
    detDepEnvase: null,
    detIndSinCosto: null,
    detIndServicio: null,
    detMntNoFact: null,
    detMntPeriodo: null,
    detPsjNac: null,
    detPsjInt: null,
    detNumInt: null,
    detCdgSIISucur: 80313898,
    detEmisorNota: 0,
    detTabPuros: 0,
    detTabCigarrillos: 0,
    detTabElaborado: 0,
    detImpVehiculo: 0,
    detTpoImp: 1,
    detTipoTransaccion: 1,
    detEventoReceptor: 'A',
    detEventoReceptorLeyenda: 'No reclamado en plazo',
    cambiarTipoTran: true,
    detPcarga: 201901,
    descTipoTransaccion: 'Del Giro',
    totalDtoiMontoImp: 0,
    totalDinrMontoIVANoR: null,
  }, {
    dhdrCodigo: 3538050325,
    dcvCodigo: 64556344,
    dcvEstadoContab: null,
    detCodigo: 1299876281,
    detTipoDoc: null,
    detRutDoc: 79882360,
    detDvDoc: '4',
    detRznSoc: 'INGENIERIA INFORMATICA ASOCIADA LIMITADA',
    detNroDoc: 189923,
    detFchDoc: '02/01/2019',
    detFecAcuse: null,
    detFecReclamado: null,
    detFecRecepcion: '02/01/2019 18:49:24',
    detMntExe: 0,
    detMntNeto: 1786262,
    detMntActFijo: 0,
    detMntIVAActFijo: 0,
    detMntIVANoRec: 0,
    detMntCodNoRec: 0,
    detMntSinCredito: 0,
    detMntIVA: 339390,
    detMntTotal: 2125652,
    detTasaImp: null,
    detAnulado: null,
    detIVARetTotal: null,
    detIVARetParcial: null,
    detIVANoRetenido: 0,
    detIVAPropio: null,
    detIVATerceros: null,
    detIVAUsoComun: 0,
    detLiqRutEmisor: null,
    detLiqDvEmisor: null,
    detLiqValComNeto: null,
    detLiqValComExe: null,
    detLiqValComIVA: null,
    detIVAFueraPlazo: null,
    detTipoDocRef: 0,
    detFolioDocRef: null,
    detExpNumId: null,
    detExpNacionalidad: null,
    detCredEc: null,
    detLey18211: null,
    detDepEnvase: null,
    detIndSinCosto: null,
    detIndServicio: null,
    detMntNoFact: null,
    detMntPeriodo: null,
    detPsjNac: null,
    detPsjInt: null,
    detNumInt: null,
    detCdgSIISucur: 0,
    detEmisorNota: 0,
    detTabPuros: 0,
    detTabCigarrillos: 0,
    detTabElaborado: 0,
    detImpVehiculo: 0,
    detTpoImp: 1,
    detTipoTransaccion: 1,
    detEventoReceptor: 'A',
    detEventoReceptorLeyenda: 'No reclamado en plazo',
    cambiarTipoTran: true,
    detPcarga: 201901,
    descTipoTransaccion: 'Del Giro',
    totalDtoiMontoImp: 0,
    totalDinrMontoIVANoR: null,
  }, {
    dhdrCodigo: 3537216165,
    dcvCodigo: 64556344,
    dcvEstadoContab: null,
    detCodigo: 1298501619,
    detTipoDoc: null,
    detRutDoc: 76578299,
    detDvDoc: '6',
    detRznSoc: 'DISEÑO SILVIO ENRIQUE VILDÓSOLA CARO E.I.R.L.',
    detNroDoc: 32,
    detFchDoc: '02/01/2019',
    detFecAcuse: null,
    detFecReclamado: null,
    detFecRecepcion: '02/01/2019 12:15:45',
    detMntExe: 0,
    detMntNeto: 45000,
    detMntActFijo: 0,
    detMntIVAActFijo: 0,
    detMntIVANoRec: 0,
    detMntCodNoRec: 0,
    detMntSinCredito: 0,
    detMntIVA: 8550,
    detMntTotal: 53550,
    detTasaImp: null,
    detAnulado: null,
    detIVARetTotal: null,
    detIVARetParcial: null,
    detIVANoRetenido: 0,
    detIVAPropio: null,
    detIVATerceros: null,
    detIVAUsoComun: 0,
    detLiqRutEmisor: null,
    detLiqDvEmisor: null,
    detLiqValComNeto: null,
    detLiqValComExe: null,
    detLiqValComIVA: null,
    detIVAFueraPlazo: null,
    detTipoDocRef: 0,
    detFolioDocRef: null,
    detExpNumId: null,
    detExpNacionalidad: null,
    detCredEc: null,
    detLey18211: null,
    detDepEnvase: null,
    detIndSinCosto: null,
    detIndServicio: null,
    detMntNoFact: null,
    detMntPeriodo: null,
    detPsjNac: null,
    detPsjInt: null,
    detNumInt: null,
    detCdgSIISucur: 80313898,
    detEmisorNota: 0,
    detTabPuros: 0,
    detTabCigarrillos: 0,
    detTabElaborado: 0,
    detImpVehiculo: 0,
    detTpoImp: 1,
    detTipoTransaccion: 1,
    detEventoReceptor: 'A',
    detEventoReceptorLeyenda: 'No reclamado en plazo',
    cambiarTipoTran: true,
    detPcarga: 201901,
    descTipoTransaccion: 'Del Giro',
    totalDtoiMontoImp: 0,
    totalDinrMontoIVANoR: null,
  },
];

// Se exportan los datos de salida
exports.outputMapperDocument = [
  {
    amount: {
      changeLaw18211: null,
      exempt: 0,
      fixedAsset: 0,
      net: 336656,
      notBillable: null,
      period: null,
      tobaccoCigar: 0,
      tobaccoElaborated: 0,
      tobaccoHavana: 0,
      total: 400621,
      withoutCredit: 0,
    },
    business: {
      dv: '6',
      name: 'TELESTAR SA',
      rut: 76429360,
    },
    date: {
      accuse: null,
      document: getDate('01/01/2019'),
      reception: getDate('02/01/2019 10:35:24'),
      reclaimed: null,
    },
    document: {
      accountingStatement: null,
      codeOffice: 0,
      codeSII: 1,
      codes: {
        dcv: 64556344,
        det: 1298116950,
      },
      containerDeposit: null,
      foreign: {
        dni: null,
        nationality: null,
      },
      id: 19157,
      indicator: {
        freeCharge: null,
        service: null,
      },
      internalSII: null,
      operation: 'COMPRA',
      passage: {
        international: null,
        national: null,
      },
      period: '201901',
      receiver: {
        code: 'A',
        description: 'No reclamado en plazo',
      },
      reference: {
        id: null,
        type: 0,
      },
      senderNote: 0,
      shippingIdentifier: 3536982623,
      specialCredit: null,
      status: null,
      transaction: {
        description: 'Del Giro',
        type: 1,
      },
    },
    paying: {
      dv: null,
      exemptAmount: null,
      netAmount: null,
      rut: null,
      taxAmount: null,
    },
    tax: {
      amount: 63965,
      amountFixedAsset: 0,
      amountNonRecoverable: 0,
      codeNonRecoverable: 0,
      commonUse: 0,
      notWithheld: 0,
      outOfTime: null,
      own: null,
      partialRetention: null,
      rate: null,
      thirdParties: null,
      totalRetention: null,
      totalTax: 0,
      totalTaxNonRecoverable: null,
      type: 1,
      vehicles: 0,
    },
    transaction: {
      queue: null,
      user: null,
    },
  }, {
    amount: {
      changeLaw18211: null,
      exempt: 0,
      fixedAsset: 0,
      net: 101000,
      notBillable: null,
      period: null,
      tobaccoCigar: 0,
      tobaccoElaborated: 0,
      tobaccoHavana: 0,
      total: 120190,
      withoutCredit: 0,
    },
    business: {
      dv: '6',
      name: 'DISEÑO SILVIO ENRIQUE VILDÓSOLA CARO E.I.R.L.',
      rut: 76578299,
    },
    date: {
      accuse: null,
      document: getDate('02/01/2019'),
      reception: getDate('02/01/2019 11:49:12'),
      reclaimed: null,
    },
    document: {
      accountingStatement: null,
      codeOffice: 80313898,
      codeSII: 2,
      codes: {
        dcv: 64556344,
        det: 1298402297,
      },
      containerDeposit: null,
      foreign: {
        dni: null,
        nationality: null,
      },
      id: 31,
      indicator: {
        freeCharge: null,
        service: null,
      },
      internalSII: null,
      operation: 'VENTA',
      passage: {
        international: null,
        national: null,
      },
      period: '201901',
      receiver: {
        code: 'A',
        description: 'No reclamado en plazo',
      },
      reference: {
        id: null,
        type: 0,
      },
      senderNote: 0,
      shippingIdentifier: 3537154869,
      specialCredit: null,
      status: null,
      transaction: {
        description: 'Del Giro',
        type: 1,
      },
    },
    paying: {
      dv: null,
      exemptAmount: null,
      netAmount: null,
      rut: null,
      taxAmount: null,
    },
    tax: {
      amount: 19190,
      amountFixedAsset: 0,
      amountNonRecoverable: 0,
      codeNonRecoverable: 0,
      commonUse: 0,
      notWithheld: 0,
      outOfTime: null,
      own: null,
      partialRetention: null,
      rate: null,
      thirdParties: null,
      totalRetention: null,
      totalTax: 0,
      totalTaxNonRecoverable: null,
      type: 1,
      vehicles: 0,
    },
    transaction: {
      queue: null,
      user: null,
    },
  }, {
    amount: {
      changeLaw18211: null,
      exempt: 0,
      fixedAsset: 0,
      net: 140000,
      notBillable: null,
      period: null,
      tobaccoCigar: 0,
      tobaccoElaborated: 0,
      tobaccoHavana: 0,
      total: 166600,
      withoutCredit: 0,
    },
    business: {
      dv: '6',
      name: 'DISEÑO SILVIO ENRIQUE VILDÓSOLA CARO E.I.R.L.',
      rut: 76578299,
    },
    date: {
      accuse: null,
      document: getDate('02/01/2019'),
      reception: getDate('02/01/2019 12:23:19'),
      reclaimed: null,
    },
    document: {
      accountingStatement: null,
      codeOffice: 80313898,
      codeSII: null,
      codes: {
        dcv: 64556344,
        det: 1298531507,
      },
      containerDeposit: null,
      foreign: {
        dni: null,
        nationality: null,
      },
      id: 33,
      indicator: {
        freeCharge: null,
        service: null,
      },
      internalSII: null,
      operation: null,
      passage: {
        international: null,
        national: null,
      },
      period: '201901',
      receiver: {
        code: 'A',
        description: 'No reclamado en plazo',
      },
      reference: {
        id: null,
        type: 0,
      },
      senderNote: 0,
      shippingIdentifier: 3537234022,
      specialCredit: null,
      status: null,
      transaction: {
        description: 'Del Giro',
        type: 1,
      },
    },
    paying: {
      dv: null,
      exemptAmount: null,
      netAmount: null,
      rut: null,
      taxAmount: null,
    },
    tax: {
      amount: 26600,
      amountFixedAsset: 0,
      amountNonRecoverable: 0,
      codeNonRecoverable: 0,
      commonUse: 0,
      notWithheld: 0,
      outOfTime: null,
      own: null,
      partialRetention: null,
      rate: null,
      thirdParties: null,
      totalRetention: null,
      totalTax: 0,
      totalTaxNonRecoverable: null,
      type: 1,
      vehicles: 0,
    },
    transaction: {
      queue: null,
      user: null,
    },
  }, {
    amount: {
      changeLaw18211: null,
      exempt: 0,
      fixedAsset: 0,
      net: 1786262,
      notBillable: null,
      period: null,
      tobaccoCigar: 0,
      tobaccoElaborated: 0,
      tobaccoHavana: 0,
      total: 2125652,
      withoutCredit: 0,
    },
    business: {
      dv: '4',
      name: 'INGENIERIA INFORMATICA ASOCIADA LIMITADA',
      rut: 79882360,
    },
    date: {
      accuse: null,
      document: getDate('02/01/2019'),
      reception: getDate('02/01/2019 18:49:24'),
      reclaimed: null,
    },
    document: {
      accountingStatement: null,
      codeOffice: 0,
      codeSII: 1,
      codes: {
        dcv: 64556344,
        det: 1299876281,
      },
      containerDeposit: null,
      foreign: {
        dni: null,
        nationality: null,
      },
      id: 189923,
      indicator: {
        freeCharge: null,
        service: null,
      },
      internalSII: null,
      operation: 'COMPRA',
      passage: {
        international: null,
        national: null,
      },
      period: '201901',
      receiver: {
        code: 'A',
        description: 'No reclamado en plazo',
      },
      reference: {
        id: null,
        type: 0,
      },
      senderNote: 0,
      shippingIdentifier: 3538050325,
      specialCredit: null,
      status: null,
      transaction: {
        description: 'Del Giro',
        type: 1,
      },
    },
    paying: {
      dv: null,
      exemptAmount: null,
      netAmount: null,
      rut: null,
      taxAmount: null,
    },
    tax: {
      amount: 339390,
      amountFixedAsset: 0,
      amountNonRecoverable: 0,
      codeNonRecoverable: 0,
      commonUse: 0,
      notWithheld: 0,
      outOfTime: null,
      own: null,
      partialRetention: null,
      rate: null,
      thirdParties: null,
      totalRetention: null,
      totalTax: 0,
      totalTaxNonRecoverable: null,
      type: 1,
      vehicles: 0,
    },
    transaction: {
      queue: '1234567890',
      user: '1-1',
    },
  },
];
