// Default mocks
module.exports = [
  {
    _id: '5a6d3b31e5b3f1153cc14b30',
    active: true,
    code: 'CODE01',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 01',
    sacraments: {
      anointingOfTheSick: true,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b31',
    active: true,
    code: 'CODE02',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 02',
    sacraments: {
      anointingOfTheSick: true,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b32',
    active: true,
    code: 'CODE03',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 03',
    sacraments: {
      anointingOfTheSick: true,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b33',
    active: true,
    code: 'CODE04',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 04',
    sacraments: {
      anointingOfTheSick: true,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b34',
    active: true,
    code: 'CODE05',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 05',
    sacraments: {
      anointingOfTheSick: true,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b35',
    active: true,
    code: 'CODE06',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 06',
    sacraments: {
      anointingOfTheSick: true,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b36',
    active: true,
    code: 'CODE07',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: '',
    sacraments: {
      anointingOfTheSick: false,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b37',
    active: true,
    code: '',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 08',
    sacraments: {
      anointingOfTheSick: false,
      baptism: true,
      confirmation: true,
      eucharist: true,
      holyOrders: true,
      marriage: true,
      reconciliation: true,
    },
  }, {
    _id: '5a6d3b31e5b3f1153cc14b38',
    active: true,
    code: '',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: 'Name 09',
    sacraments: {},
  }, {
    _id: '5a6d3b31e5b3f1153cc14b39',
    active: true,
    code: '',
    logs: {
      isDeleted: false,
      test: true,
    },
    name: '',
    sacraments: {},
  },
];
